#!/bin/sh

# remove whitespace from end of lines

git diff --name-only --cached | while read file ; do

egrep '[ ]+$' $file && cat $file | sed 's/[ \r]\+$//g' > $file.new && mv $file.new $file || exit 0

done

# CR:

