#!/bin/sh

# remove whitespace from end of lines

git diff --name-only --cached | while read file ; do

grep '  *$' $file && cat $file | sed 's/  *$//g' > $file.new && mv $file.new $file || exit 0

done
